redis_config:
  host: '127.0.0.1'
  port: 49155
  db: 0
  password: 'redispw'
extractor:
  extraction_function: "extract_images"
  strategy_module: "image"
  input_path: "dogs"
loader:
  loading_function: "load_image_to_redis"
  strategy_module: "image"
logger:
  logger_name: "rolling_logger"
  base_level: DEBUG
  fmt: "%(asctime)s - %(levelname)s - %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"
  debug_file_path: "logs/debug.log"
  info_file_path: "logs/info.log"
  warning_file_path: "logs/warning.log"
  error_file_path: "logs/error.log"
  critical_file_path: "logs/critical.log"
