redis_config:
  host: '127.0.0.1'
  port: 49155
  db: 0
  password: 'redispw'
extractor:
  extraction_function: "extract_binary_files"
  package_name: "utils"
  sub_package_name: "dbs"
  strategy_module: "redis"
  extract_method: "get"
  input_path: "dogs"
loader:
  loading_function: "load_binary_files"
  package_name: "utils"
  sub_package_name: "dbs"
  strategy_module: "redis"
  load_method: "set"
logger:
  logger_name: "rolling_logger"
  base_level: DEBUG
  fmt: "%(asctime)s - %(levelname)s - %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    - "FileHandler"
    - "StreamHandler"
  log_file_path: "logs/log.log"
